### PR TITLE
Fix JSON Parse Error

### LINKED ISSUE #16: JSON Parse Error when function contains logging
When the lambda function being tested contains logging, JS runner incorrectly attempts to JSON.parse the entire stdout.

### PR DESCRIPTION
**Pull request by patrickhousley**
Lambda function stdout is now split on `\n` character to get the last value. This assumes the last value in stdout is the result object from the Lambda function. If it cannot be parsed, it is returned as a string. If stdout has no entries, an empty string will be returned to the caller.

Fixes #16

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -76,6 +76,21 @@ resetMock({status: 0, stdout: 'null'})
 result = dockerLambda({returnSpawnResult: true})
 result.should.eql({status: 0, stdout: 'null'})
 
+// Should not fail if stdout contains logging
+resetMock({status: 0, stdout: 'Test\nResult\n{"success":true}'})
+result = dockerLambda()
+result.should.eql({success: true})
+
+// Should return last stdout entry if it's not JSON
```
Comment (mhart) [inline test.js]: I'm not sure this is correct – the result should only ever come from the invocation of the Lambda function. I think it's probably best to just return `undefined` if the `JSON.parse` fails, because that should be an anomaly (like the function crashed or something).

File: test.js [hunk 2]
```diff
@@ -76,6 +76,21 @@ resetMock({status: 0, stdout: 'null'})
...
+resetMock({status: 0, stdout: 'Test\nResult\nsuccess'})
+result = dockerLambda()
+result.should.eql('success')
+
+// Should return empty string when the function was successful but there is no stdout
```
Comment (mhart) [inline test.js]: Same as above – I'm not sure `stdout` would ever be just an empty string?

**Comment by mhart** [comment]
I kinda like this approach – thanks for the PR!

I made a couple of comments regarding behavior if the final line *can't* be parsed – I don't think it should be returned regardless, because it's almost definitely not the result of the lambda function

File: test.js [hunk 3]
```diff
@@ -76,6 +76,21 @@ resetMock({status: 0, stdout: 'null'})
...
 
+// Should not fail if stdout contains logging
+resetMock({status: 0, stdout: 'Test\nResult\n{"success":true}'})
+result = dockerLambda()
+result.should.eql({success: true})
+
+// Should return undefined if last stdout entry cannot be parsed
+resetMock({status: 0, stdout: 'Test\nResult\nsuccess'})
+result = dockerLambda()
+result === void 0 // Result is undefined and does not contain `should`
```
Comment (mhart) [inline test.js]: You'll need to assert something here. Just `should.not.exist(result)` would be fine 👍

File: test.js [hunk 4]
```diff
@@ -76,6 +76,21 @@ resetMock({status: 0, stdout: 'null'})
...
+
+// Should return undefined when function was successful but there is no stdout
+resetMock({status: 0, stdout: ''})
+result = dockerLambda()
+result === void 0 // Result is undefined and does not contain `should`
```
Comment (mhart) [inline test.js]: Same as above

File: index.js [hunk 5]
```diff
@@ -53,5 +53,14 @@ module.exports = function runSync(options) {
...
-  return JSON.parse(spawnResult.stdout)
+  var stdout = spawnResult.stdout.split('\n')
+  try {
+    return JSON.parse(stdout[stdout.length - 1])
+  } catch (err) {
+    // This should return undefined and not null to indicate that either the
+    // Lambda function had not output or the output could not be parsed. Both
+    // cases should be rare and are most likely the result of an issue with the
+    // Lambda function.
+    return undefined
```
Comment (mhart) [inline index.js]: I think it's cleaner just to `return` – but don't really mind

**Comment by mhart** [comment]
Niiice – thanks for all that!

**Comment by mhart** [comment]
Published as v0.10.0 – thanks so much for the PR!
